#pragma once
#include <Hypo/Core.h>

#define HYPO_ENOERR 0


#if defined(HYPO_PLATFORM_WINDOWS)
#include <winsock2.h>
#include <ws2tcpip.h>
#define HYPO_INVALID_SOCKET  INVALID_SOCKET
#define hypo_socket_t        SOCKET
#define hypo_socklen_t       int
#define hypo_ioctl_request_t int
#define hypo_closesocket(s)  closesocket(s)
#define HYPO_EINTR           WSAEINTR
#define HYPO_EACCES          WSAEACCES
#define HYPO_EFAULT          WSAEFAULT
#define HYPO_EINVAL          WSAEINVAL
#define HYPO_EMFILE          WSAEMFILE
#define HYPO_EAGAIN          WSAEWOULDBLOCK
#define HYPO_EWOULDBLOCK     WSAEWOULDBLOCK
#define HYPO_EINPROGRESS     WSAEINPROGRESS
#define HYPO_EALREADY        WSAEALREADY
#define HYPO_ENOTSOCK        WSAENOTSOCK
#define HYPO_EDESTADDRREQ    WSAEDESTADDRREQ
#define HYPO_EMSGSIZE        WSAEMSGSIZE
#define HYPO_EPROTOTYPE      WSAEPROTOTYPE
#define HYPO_ENOPROTOOPT     WSAENOPROTOOPT
#define HYPO_EPROTONOSUPPORT WSAEPROTONOSUPPORT
#define HYPO_ESOCKTNOSUPPORT WSAESOCKTNOSUPPORT
#define HYPO_ENOTSUP         WSAEOPNOTSUPP
#define HYPO_EPFNOSUPPORT    WSAEPFNOSUPPORT
#define HYPO_EAFNOSUPPORT    WSAEAFNOSUPPORT
#define HYPO_EADDRINUSE      WSAEADDRINUSE
#define HYPO_EADDRNOTAVAIL   WSAEADDRNOTAVAIL
#define HYPO_ENETDOWN        WSAENETDOWN
#define HYPO_ENETUNREACH     WSAENETUNREACH
#define HYPO_ENETRESET       WSAENETRESET
#define HYPO_ECONNABORTED    WSAECONNABORTED
#define HYPO_ECONNRESET      WSAECONNRESET
#define HYPO_ENOBUFS         WSAENOBUFS
#define HYPO_EISCONN         WSAEISCONN
#define HYPO_ENOTCONN        WSAENOTCONN
#define HYPO_ESHUTDOWN       WSAESHUTDOWN
#define HYPO_ETIMEDOUT       WSAETIMEDOUT
#define HYPO_ECONNREFUSED    WSAECONNREFUSED
#define HYPO_EHOSTDOWN       WSAEHOSTDOWN
#define HYPO_EHOSTUNREACH    WSAEHOSTUNREACH
#define HYPO_ESYSNOTREADY    WSASYSNOTREADY
#define HYPO_ENOTINIT        WSANOTINITIALISED
#define HYPO_HOST_NOT_FOUND  WSAHOST_NOT_FOUND
#define HYPO_TRY_AGAIN       WSATRY_AGAIN
#define HYPO_NO_RECOVERY     WSANO_RECOVERY
#define HYPO_NO_DATA         WSANO_DATA

#ifndef ADDRESS_FAMILY
#define ADDRESS_FAMILY USHORT
#endif

#endif
